from typing import Dict, List, Type
from pydantic import BaseModel, Field
from core.infrastructure.ai_adapters import (
    BaseAIProvider, 
    OpenAIAdapter, 
    ClaudeAdapter, 
    GeminiAdapter, 
    DeepSeekAdapter, 
    OpenRouterAdapter,
    AIResult,
    ImageResult
)

class DecomposedTasksSpec(BaseModel):
    """
    Decomposed blueprint parsed from a single business prompt.
    """
    business_name: str = Field(description="Name of the business generated by the agent")
    tagline: str = Field(description="Catchy tagline or slogan")
    theme_colors: List[str] = Field(description="Array of hex colors (3-5 items) fitting the brand theme")
    pages_to_generate: List[str] = Field(description="Slug list of pages needed (e.g. ['index', 'products', 'about'])")
    logo_generation_prompt: str = Field(description="Detailed image prompt for logo generation")
    banner_generation_prompt: str = Field(description="Detailed image prompt for hero/banner imagery")
    copywriting_tone: str = Field(description="Tone of voice (e.g. 'professional', 'cyberpunk', 'organic')")
    seo_keywords: List[str] = Field(description="Target SEO keyword terms for marketing")


class AIRouterService:
    """
    Core AI task manager and router. Decouples provider orchestration.
    """
    def __init__(self):
        self._providers: Dict[str, BaseAIProvider] = {}
        self._register_default_providers()

    def _register_default_providers(self):
        self.register_provider("openai", OpenAIAdapter())
        self.register_provider("claude", ClaudeAdapter())
        self.register_provider("gemini", GeminiAdapter())
        self.register_provider("deepseek", DeepSeekAdapter())
        self.register_provider("openrouter", OpenRouterAdapter())

    def register_provider(self, name: str, provider: BaseAIProvider):
        self._providers[name] = provider

    def get_provider(self, name: str) -> BaseAIProvider:
        if name not in self._providers:
            raise ValueError(f"AI Provider '{name}' is not registered.")
        return self._providers[name]

    def select_best_provider_for_task(self, task_type: str) -> str:
        """
        Dynamic routing policy based on performance, cost, and provider features.
        """
        routing_policy = {
            "decompose_intent": "openai",  # Best-in-class structured output formatting
            "layout_code_generation": "claude",  # Highly competent code logic synthesizers
            "copywriting_text": "deepseek",  # Cost-effective, high-volume semantic text
            "image_generation": "openai",  # Native DALL-E 3 image generation
            "general_chat": "gemini",  # Native quick dialogue
        }
        return routing_policy.get(task_type, "openai")

    def parse_intent(self, user_prompt: str) -> DecomposedTasksSpec:
        """
        Decomposes the user's prompt into detailed architectural specifications.
        """
        provider_name = self.select_best_provider_for_task("decompose_intent")
        provider = self.get_provider(provider_name)
        
        system_instruction = (
            "You are the Lead Business Architect of BevHub AI. Your job is to parse the user's "
            "business request and decompose it into a highly detailed structure."
        )
        
        # Requests structured output from adapter
        result = provider.generate_text(
            prompt=user_prompt,
            system_instruction=system_instruction,
            response_schema=DecomposedTasksSpec
        )
        
        # Return parsed pydantic model directly
        return DecomposedTasksSpec.model_validate_json(result.text)

    def generate_text_content(self, prompt: str, system_instruction: str | None = None) -> AIResult:
        provider_name = self.select_best_provider_for_task("copywriting_text")
        provider = self.get_provider(provider_name)
        return provider.generate_text(prompt, system_instruction)

    def generate_asset_image(self, prompt: str, size: str = "1024x1024") -> ImageResult:
        provider_name = self.select_best_provider_for_task("image_generation")
        provider = self.get_provider(provider_name)
        return provider.generate_image(prompt, size)
