# Generated by Django 5.2.16 on 2026-07-16 15:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_aitask_projectfile"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserJourneyEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("step", models.CharField(db_index=True, max_length=100)),
                ("status", models.CharField(default="success", max_length=50)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("duration_ms", models.IntegerField(default=0)),
                (
                    "workspace_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("browser", models.CharField(blank=True, max_length=255)),
                ("device", models.CharField(blank=True, max_length=255)),
                ("version", models.CharField(default="v1.0.0-rc", max_length=50)),
                (
                    "logs",
                    models.TextField(
                        blank=True,
                        help_text="Collect Logs, Planner State, Worker, Model, Context, Prompt, Stack Trace",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="journey_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_journey_events",
                "indexes": [
                    models.Index(
                        fields=["step", "status"], name="user_journe_step_6b3bc8_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="user_journe_created_0c94a9_idx"
                    ),
                ],
            },
        ),
    ]
