# Generated by Django 5.2.16 on 2026-07-19 16:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_userjourneyevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("overall_score", models.IntegerField()),
                ("architecture_score", models.IntegerField()),
                ("performance_score", models.IntegerField()),
                ("security_score", models.IntegerField()),
                ("seo_score", models.IntegerField()),
                ("accessibility_score", models.IntegerField()),
                ("ux_score", models.IntegerField()),
                ("typescript_score", models.IntegerField()),
                ("react_score", models.IntegerField()),
                ("deployment_score", models.IntegerField()),
                (
                    "issues",
                    models.JSONField(
                        default=list, help_text="Detailed issues identified"
                    ),
                ),
                (
                    "recommendations",
                    models.JSONField(default=list, help_text="List of recommendations"),
                ),
                (
                    "raw_report",
                    models.JSONField(
                        default=dict,
                        help_text="Raw JSON response from the Review Engine",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "db_table": "project_reviews",
            },
        ),
    ]
