# Generated by Django 5.2.16 on 2026-07-20 07:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_projectreview"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "snapshot_data",
                    models.JSONField(help_text="Complete files and pages data backup"),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "db_table": "project_snapshots",
            },
        ),
        migrations.CreateModel(
            name="ProjectFixRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("before_score", models.IntegerField()),
                ("after_score", models.IntegerField()),
                ("fixed_count", models.IntegerField(default=0)),
                ("remaining_count", models.IntegerField(default=0)),
                ("rollback_applied", models.BooleanField(default=False)),
                (
                    "logs",
                    models.JSONField(
                        default=list,
                        help_text="Detailed step-by-step logs of executed fixes",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fix_runs",
                        to="core.project",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.projectsnapshot",
                    ),
                ),
            ],
            options={
                "db_table": "project_fix_runs",
            },
        ),
    ]
