# Generated by Django 5.2.16 on 2026-07-20 08:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_projectsnapshot_projectfixrun"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenerationStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("step_name", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("FAILED", "Failed"),
                            ("SUCCESS", "Success"),
                        ],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.FloatField(default=0.0)),
                ("tokens_used", models.IntegerField(default=0)),
                ("model_name", models.CharField(blank=True, max_length=100)),
                (
                    "cost",
                    models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="core.aitask",
                    ),
                ),
            ],
            options={
                "db_table": "generation_steps",
                "ordering": ["created_at"],
            },
        ),
    ]
