# Generated by Django 5.2.16 on 2026-07-12 10:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AICreditBalance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=100.0, max_digits=12),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_balance",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "ai_credit_balances",
            },
        ),
        migrations.CreateModel(
            name="ProjectMemory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("industry", models.CharField(blank=True, max_length=255)),
                ("target_audience", models.TextField(blank=True)),
                ("brand_voice", models.CharField(blank=True, max_length=100)),
                (
                    "preferred_language",
                    models.CharField(default="English", max_length=50),
                ),
                (
                    "products_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Metadata of products or services offered",
                    ),
                ),
                (
                    "user_preferences",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom key-value user preferences",
                    ),
                ),
                (
                    "metadata_store",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Historical values from previous AI outputs",
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memory",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "db_table": "project_memories",
            },
        ),
        migrations.CreateModel(
            name="UserMemory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "writing_style",
                    models.CharField(default="Professional", max_length=100),
                ),
                ("favorite_colors", models.JSONField(blank=True, default=list)),
                (
                    "preferred_language",
                    models.CharField(default="English", max_length=50),
                ),
                ("last_active_project_id", models.UUIDField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memory",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_memories",
            },
        ),
        migrations.CreateModel(
            name="AICreditTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                (
                    "amount_consumed",
                    models.DecimalField(decimal_places=4, max_digits=8),
                ),
                ("task_description", models.CharField(max_length=255)),
                ("is_image_generation", models.BooleanField(default=False)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_transactions",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "ai_credit_transactions",
                "indexes": [
                    models.Index(
                        fields=["tenant", "created_at"],
                        name="ai_credit_t_tenant__48c6ad_idx",
                    )
                ],
            },
        ),
    ]
